# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='avatar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='created_ts',
            field=models.IntegerField(default=1552311528),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='language',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='last_login_ts',
            field=models.IntegerField(default=1552311528),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='last_ping_ts',
            field=models.IntegerField(default=1552311528),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='mobile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='province',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='session_key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='unionid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='wxid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
